from PyQt5 import QtCore, QtWidgets
from button_actions import ButtonActions


class GraphicalUI(ButtonActions):

    def ui_setup(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(510, 300)

        self.x_button = QtWidgets.QPushButton(Form)
        self.y_button = QtWidgets.QPushButton(Form)
        self.sq_button = QtWidgets.QPushButton(Form)
        self.pow_button = QtWidgets.QPushButton(Form)
        self.euler_button = QtWidgets.QPushButton(Form)
        self.l_parenthesis_button = QtWidgets.QPushButton(Form)
        self.r_parenthesis_button = QtWidgets.QPushButton(Form)
        self.ln_button = QtWidgets.QPushButton(Form)
        self.abs_button = QtWidgets.QPushButton(Form)
        self.log_button = QtWidgets.QPushButton(Form)
        self.pi_button = QtWidgets.QPushButton(Form)
        self.nine_button = QtWidgets.QPushButton(Form)
        self.seven_button = QtWidgets.QPushButton(Form)
        self.four_button = QtWidgets.QPushButton(Form)
        self.five_button = QtWidgets.QPushButton(Form)
        self.star_button = QtWidgets.QPushButton(Form)
        self.six_button = QtWidgets.QPushButton(Form)
        self.eight_button = QtWidgets.QPushButton(Form)
        self.root_button = QtWidgets.QPushButton(Form)
        self.divide_button = QtWidgets.QPushButton(Form)
        self.three_button = QtWidgets.QPushButton(Form)
        self.one_button = QtWidgets.QPushButton(Form)
        self.dec_button = QtWidgets.QPushButton(Form)
        self.zero_button = QtWidgets.QPushButton(Form)
        self.plus_button = QtWidgets.QPushButton(Form)
        self.clear_button = QtWidgets.QPushButton(Form)
        self.two_button = QtWidgets.QPushButton(Form)
        self.minus_button = QtWidgets.QPushButton(Form)
        self.sin_button = QtWidgets.QPushButton(Form)
        self.graph_button = QtWidgets.QPushButton(Form)
        self.exit_button = QtWidgets.QPushButton(Form)
        self.enter_button = QtWidgets.QPushButton(Form)
        self.arcsin_button = QtWidgets.QPushButton(Form)
        self.sinh_button = QtWidgets.QPushButton(Form)
        self.arccos_button = QtWidgets.QPushButton(Form)
        self.cos_button = QtWidgets.QPushButton(Form)
        self.cosh_button = QtWidgets.QPushButton(Form)
        self.arctan_button = QtWidgets.QPushButton(Form)
        self.tan_button = QtWidgets.QPushButton(Form)
        self.tanh_button = QtWidgets.QPushButton(Form)
        self.sec_button = QtWidgets.QPushButton(Form)
        self.coth_button = QtWidgets.QPushButton(Form)
        self.arccsc_button = QtWidgets.QPushButton(Form)
        self.csc_button = QtWidgets.QPushButton(Form)
        self.arccot_button = QtWidgets.QPushButton(Form)
        self.sech_button = QtWidgets.QPushButton(Form)
        self.csch_button = QtWidgets.QPushButton(Form)
        self.cot_button = QtWidgets.QPushButton(Form)
        self.arcsec_button = QtWidgets.QPushButton(Form)
        self.z_funcTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.z_funcLabel = QtWidgets.QLabel(Form)
        self.lines_textEdit = QtWidgets.QPlainTextEdit(Form)
        self.smooth_textEdit = QtWidgets.QPlainTextEdit(Form)
        self.lines_label = QtWidgets.QLabel(Form)
        self.smooth_label = QtWidgets.QLabel(Form)

        self.x_button.setGeometry(QtCore.QRect(10, 130, 41, 41))
        self.x_button.setObjectName("x_button")
        self.x_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.x_button.clicked.connect(self.x_display)

        self.y_button.setGeometry(QtCore.QRect(50, 130, 41, 41))
        self.y_button.setObjectName("y_button")
        self.y_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.y_button.clicked.connect(self.y_display)

        self.sq_button.setGeometry(QtCore.QRect(90, 130, 41, 41))
        self.sq_button.setObjectName("sq_button")
        self.sq_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.pow_button.setGeometry(QtCore.QRect(130, 130, 41, 41))
        self.pow_button.setObjectName("pow_button")
        self.pow_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.euler_button.setGeometry(QtCore.QRect(90, 170, 41, 41))
        self.euler_button.setObjectName("euler_button")
        self.euler_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.l_parenthesis_button.setGeometry(QtCore.QRect(10, 170, 41, 41))
        self.l_parenthesis_button.setObjectName("l_parenth_button")
        self.l_parenthesis_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.l_parenthesis_button.clicked.connect(self.lpar_display)

        self.r_parenthesis_button.setGeometry(QtCore.QRect(50, 170, 41, 41))
        self.r_parenthesis_button.setObjectName("r_parenth_button")
        self.r_parenthesis_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.r_parenthesis_button.clicked.connect(self.rpar_display)

        self.ln_button.setGeometry(QtCore.QRect(130, 170, 41, 41))
        self.ln_button.setObjectName("ln_button")
        self.ln_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.abs_button.setGeometry(QtCore.QRect(90, 210, 41, 41))
        self.abs_button.setObjectName("abs_button")
        self.abs_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.log_button.setGeometry(QtCore.QRect(10, 210, 41, 41))
        self.log_button.setObjectName("log_button")
        self.log_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.root_button.setGeometry(QtCore.QRect(50, 210, 41, 41))
        self.root_button.setObjectName("root_button")
        self.root_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.pi_button.setGeometry(QtCore.QRect(130, 210, 41, 41))
        self.pi_button.setObjectName("pi_button")
        self.pi_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.nine_button.setGeometry(QtCore.QRect(260, 130, 41, 41))
        self.nine_button.setObjectName("nine_button")
        self.nine_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.seven_button.setGeometry(QtCore.QRect(180, 130, 41, 41))
        self.seven_button.setObjectName("seven_button")
        self.seven_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.four_button.setGeometry(QtCore.QRect(180, 170, 41, 41))
        self.four_button.setObjectName("four_button")
        self.four_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.five_button.setGeometry(QtCore.QRect(220, 170, 41, 41))
        self.five_button.setObjectName("five_button")
        self.five_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.star_button.setGeometry(QtCore.QRect(300, 170, 41, 41))
        self.star_button.setObjectName("star_button")
        self.star_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.star_button.clicked.connect(self.star_display)

        self.six_button.setGeometry(QtCore.QRect(260, 170, 41, 41))
        self.six_button.setObjectName("six_button")
        self.six_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.eight_button.setGeometry(QtCore.QRect(220, 130, 41, 41))
        self.eight_button.setObjectName("eight_button")
        self.eight_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.divide_button.setGeometry(QtCore.QRect(300, 130, 41, 41))
        self.divide_button.setObjectName("divide_button")
        self.divide_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.three_button.setGeometry(QtCore.QRect(260, 210, 41, 41))
        self.three_button.setObjectName("three_button")
        self.three_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.one_button.setGeometry(QtCore.QRect(180, 210, 41, 41))
        self.one_button.setObjectName("one_button")
        self.one_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.dec_button.setGeometry(QtCore.QRect(180, 250, 41, 41))
        self.dec_button.setObjectName("dec_button")
        self.dec_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.zero_button.setGeometry(QtCore.QRect(220, 250, 41, 41))
        self.zero_button.setObjectName("zero_button")
        self.zero_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.plus_button.setGeometry(QtCore.QRect(300, 250, 41, 41))
        self.plus_button.setObjectName("plus_button")
        self.plus_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.clear_button.setGeometry(QtCore.QRect(260, 250, 41, 41))
        self.clear_button.setObjectName("clear_button")
        self.clear_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.clear_button.clicked.connect(self.clear_display)

        self.two_button.setGeometry(QtCore.QRect(220, 210, 41, 41))
        self.two_button.setObjectName("two_button")
        self.two_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.minus_button.setGeometry(QtCore.QRect(300, 210, 41, 41))
        self.minus_button.setObjectName("minus_button")
        self.minus_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.sin_button.setGeometry(QtCore.QRect(350, 50, 51, 41))
        self.sin_button.setObjectName("sin_button")
        self.sin_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.sin_button.clicked.connect(self.sin_display)

        self.graph_button.setGeometry(QtCore.QRect(380, 10, 91, 41))
        self.graph_button.setObjectName("graph_button")
        self.graph_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.graph_button.clicked.connect(self.graph_pressed)

        self.exit_button.setGeometry(QtCore.QRect(10, 250, 81, 41))
        self.exit_button.setObjectName("exit_button")
        self.exit_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.exit_button.clicked.connect(self.close_prog)

        self.enter_button.setGeometry(QtCore.QRect(90, 250, 81, 41))
        self.enter_button.setObjectName("enter_button")
        self.enter_button.setStyleSheet("QPushButton:pressed { background-color: white }")
        self.enter_button.clicked.connect(self.enter)

        self.arcsin_button.setGeometry(QtCore.QRect(400, 50, 51, 41))
        self.arcsin_button.setObjectName("arcsin_button")
        self.arcsin_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.sinh_button.setGeometry(QtCore.QRect(450, 50, 51, 41))
        self.sinh_button.setObjectName("sinh_button")
        self.sinh_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.arccos_button.setGeometry(QtCore.QRect(400, 90, 51, 41))
        self.arccos_button.setObjectName("arccos_button")
        self.arccos_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.cos_button.setGeometry(QtCore.QRect(350, 90, 51, 41))
        self.cos_button.setObjectName("cos_button")
        self.cos_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.cosh_button.setGeometry(QtCore.QRect(450, 90, 51, 41))
        self.cosh_button.setObjectName("cosh_button")
        self.cosh_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.arctan_button.setGeometry(QtCore.QRect(400, 130, 51, 41))
        self.arctan_button.setObjectName("arctan_button")
        self.arctan_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.tan_button.setGeometry(QtCore.QRect(350, 130, 51, 41))
        self.tan_button.setObjectName("tan_button")
        self.tan_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.tanh_button.setGeometry(QtCore.QRect(450, 130, 51, 41))
        self.tanh_button.setObjectName("tanh_button")
        self.tanh_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.sec_button.setGeometry(QtCore.QRect(350, 210, 51, 41))
        self.sec_button.setObjectName("sec_button")
        self.sec_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.coth_button.setGeometry(QtCore.QRect(450, 250, 51, 41))
        self.coth_button.setObjectName("coth_button")
        self.coth_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.arccsc_button.setGeometry(QtCore.QRect(400, 170, 51, 41))
        self.arccsc_button.setObjectName("arccsc_button")
        self.arccsc_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.csc_button.setGeometry(QtCore.QRect(350, 170, 51, 41))
        self.csc_button.setObjectName("csc_button")
        self.csc_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.arccot_button.setGeometry(QtCore.QRect(400, 250, 51, 41))
        self.arccot_button.setObjectName("arccot_button")
        self.arccot_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.sech_button.setGeometry(QtCore.QRect(450, 210, 51, 41))
        self.sech_button.setObjectName("sech_button")
        self.sech_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.csch_button.setGeometry(QtCore.QRect(450, 170, 51, 41))
        self.csch_button.setObjectName("csch_button")
        self.csch_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.cot_button.setGeometry(QtCore.QRect(350, 250, 51, 41))
        self.cot_button.setObjectName("cot_button")
        self.cot_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.arcsec_button.setGeometry(QtCore.QRect(400, 210, 51, 41))
        self.arcsec_button.setObjectName("arcsec_button")
        self.arcsec_button.setStyleSheet("QPushButton:pressed { background-color: white }")

        self.z_funcTextEdit.setGeometry(QtCore.QRect(70, 10, 271, 31))
        self.z_funcTextEdit.setObjectName("z_funcTextEdit")
        self.z_funcTextEdit.setReadOnly(True)

        self.z_funcLabel.setGeometry(QtCore.QRect(40, 10, 31, 31))
        self.z_funcLabel.setObjectName("z_funcLabel")

        self.lines_textEdit.setGeometry(QtCore.QRect(70, 50, 271, 31))
        self.lines_textEdit.setObjectName("lines_textEdit")
        self.lines_textEdit.setReadOnly(True)

        self.smooth_textEdit.setGeometry(QtCore.QRect(70, 90, 271, 31))
        self.smooth_textEdit.setObjectName("smooth_textEdit")

        self.lines_label.setGeometry(QtCore.QRect(30, 50, 40, 31))
        self.lines_label.setObjectName("lines_label")

        self.smooth_label.setGeometry(QtCore.QRect(10, 90, 61, 31))
        self.smooth_label.setObjectName("smooth_label")

        self.retranslate_ui(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslate_ui(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "3D Plotter"))
        self.x_button.setText(_translate("Form", "\U0001D499"))
        self.y_button.setText(_translate("Form", "\U0001D49A"))
        self.sq_button.setText(_translate("Form", "a²"))
        self.pow_button.setText(_translate("Form", "a\u207F"))
        self.euler_button.setText(_translate("Form", "\u212F"))
        self.l_parenthesis_button.setText(_translate("Form", "("))
        self.r_parenthesis_button.setText(_translate("Form", ")"))
        self.ln_button.setText(_translate("Form", "ln"))
        self.abs_button.setText(_translate("Form", "|a|"))
        self.log_button.setText(_translate("Form", "log"))
        self.root_button.setText(_translate("Form", "\u221A"))
        self.pi_button.setText(_translate("Form", "\U0001D70B"))
        self.nine_button.setText(_translate("Form", "9"))
        self.seven_button.setText(_translate("Form", "7"))
        self.four_button.setText(_translate("Form", "4"))
        self.five_button.setText(_translate("Form", "5"))
        self.star_button.setText(_translate("Form", "*"))
        self.six_button.setText(_translate("Form", "6"))
        self.eight_button.setText(_translate("Form", "8"))
        self.divide_button.setText(_translate("Form", "/"))
        self.three_button.setText(_translate("Form", "3"))
        self.one_button.setText(_translate("Form", "1"))
        self.dec_button.setText(_translate("Form", "."))
        self.zero_button.setText(_translate("Form", "0"))
        self.plus_button.setText(_translate("Form", "+"))
        self.clear_button.setText(_translate("Form", "CLR"))
        self.two_button.setText(_translate("Form", "2"))
        self.minus_button.setText(_translate("Form", "-"))
        self.sin_button.setText(_translate("Form", "sin"))
        self.graph_button.setText(_translate("Form", "GRAPH"))
        self.exit_button.setText(_translate("Form", "EXIT"))
        self.enter_button.setText(_translate("Form", "ENTER"))
        self.arcsin_button.setText(_translate("Form", "arcsin"))
        self.sinh_button.setText(_translate("Form", "sinh"))
        self.arccos_button.setText(_translate("Form", "arccos"))
        self.cos_button.setText(_translate("Form", "cos"))
        self.cosh_button.setText(_translate("Form", "cosh"))
        self.arctan_button.setText(_translate("Form", "arctan"))
        self.tan_button.setText(_translate("Form", "tan"))
        self.tanh_button.setText(_translate("Form", "tanh"))
        self.sec_button.setText(_translate("Form", "sec"))
        self.coth_button.setText(_translate("Form", "coth"))
        self.arccsc_button.setText(_translate("Form", "arccsc"))
        self.csc_button.setText(_translate("Form", "csc"))
        self.arccot_button.setText(_translate("Form", "arccot"))
        self.sech_button.setText(_translate("Form", "sech"))
        self.csch_button.setText(_translate("Form", "csch"))
        self.cot_button.setText(_translate("Form", "cot"))
        self.arcsec_button.setText(_translate("Form", "arcsec"))
        self.z_funcLabel.setText(_translate("Form", "\U0001D4E9 ="))
        self.lines_label.setText(_translate("Form", "LINES:"))
        self.smooth_label.setText(_translate("Form", "SMOOTH:"))